name: Day Challenge
run-name: ${{ github.actor }} is running Day Challenge 🚀
on: [push]
jobs:
  Day-Challenge-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: run playbook
        shell: bash
        run: ansible-playbook ansible.yml      
